### ISSUE TITLE
Issue: Text color change

### ISSUE THREAD

**Issue by Chintan1998** [HeinrichReimer/material-drawer#19]
So, yes, this is probably the most stupidest issue but I legit, am having diffculties changing the text colour in the drawer. Whats the easiest way to change the text color?

**Comment by FabianTerhorst** [comment]
add a attribute mTextColor in the DrawerItem
add setter and getter, too

and add 

if (item.getColor() != 0) {
       viewHolder.getTextViewPrimary().setTextColor(item.getColor());
}

in DrawerAdapter

dont forgot to notifydatachanges in setcolor method.

**Comment by HeinrichReimer** [comment]
The library will use independent text colors in the next update so the text will be readable irrespective of your main theme.
