### ISSUE TITLE
Add Drawer Shadow

### ISSUE THREAD

**Issue by JaisonBrooks** [HeinrichReimer/material-drawer#20]
IT'd be awesome if you create a method to easily set the drawer shadow on the drawer. Regardless this is great work and progress so far!! keep it up

**Comment by i906** [comment]
I am using this for setting shadows
```java
mDrawerLayout.setDrawerShadow(R.drawable.drawer_shadow, Gravity.START);
```

**Comment by HeinrichReimer** [comment]
I'll add this today to the custom DrawerLayout implementation and then I'll release it
