### ISSUE TITLE
Ability to programmatically open/close drawers

### ISSUE THREAD

**Issue by theblixguy** [HeinrichReimer/material-drawer#22]
Please add a method to open/close drawer from code

**Comment by HeinrichReimer** [comment]
If you use the new `DrawerFrameLayout` you can simply open and close the drawer with `drawerFrameLayout.openDrawer()` and `drawerFrameLayout.closeDrawer()`

**Comment by SimplyY** [comment]
I want to control the time that drawer's close animation spend.

The reason why i want do it is that when i use setOnItemClickListener() to change fragment, i find drawer's close animation is not smooth.

Now, i solved it by timer.
first close drawer and 
handler.postDelayed(runnable, 320)  then change fragment .

but i think it is not a good way to solve the problem.The delayed time is long.I need your help.
