### ISSUE TITLE
Drawer header without a profile

### ISSUE THREAD

**Issue by scan** [HeinrichReimer/material-drawer#24]
Without the profile header, the drawer looks kinda blank. But my app doesn't have user accounts.

I know the guidelines for material design say the top of the drawer should contain profiles, but if there aren't any in the app, it should be possible to set a header image/drawable without profiles.

As it is right now, the profile top will not show up at all if there is not a profile image and name set (not even empty strings are allowed), so it's not possible to re-use that part.

**Comment by vbauer** [comment]
:+1:

**Comment by HeinrichReimer** [comment]
Fixed
