### ISSUE TITLE
Problem: Back Arrow Instead of Hamgurger Icon

### ISSUE THREAD

**Issue by stripathi669** [HeinrichReimer/material-drawer#25]
I am facing two issues implementing this the library.

1. The hamburger Icon to open the the drawer doesn't show up normally. If I use set Navigation icon property of the toolbar, Back Arrow Icon shows up, irrespective of what Icon I choose. Though I can pull out the drawer, I can't open it using icon on the toolbar.

2. I can't seem to be able to set profile background. Irrespective what drawable/bitmap I choose, the background 

is a grey.

I have attached screenshots for both the issues.

![screenshot_2015-01-04-12-43-11](https://cloud.githubusercontent.com/assets/7647281/5605118/c5965916-940f-11e4-9932-33814fd1b989.png)
![screenshot_2015-01-04-12-41-21](https://cloud.githubusercontent.com/assets/7647281/5605119/c599bc78-940f-11e4-8978-23054fcd6dd7.png)

**Comment by HeinrichReimer** [comment]
For your first issue check the demo code that I'll release soon. I guess you're not using the [ActionBarDrawerToggle](https://developer.android.com/reference/android/support/v7/app/ActionBarDrawerToggle.html).

Would be great if you post your code here where you set the profile background.

**Comment by stripathi669** [comment]
Hey, Thanks. I will wait for the sample.
    
I have posted the section where is I create and assign profile, toolbar and background.

==========================

private void makeDrawer() {


        profile = new DrawerProfile()
                .setAvatar(getResources().getDrawable(R.drawable.photo))
                .setBackground(getResources().getDrawable(R.drawable.bamboo))
                .setName("Abraham Lincoln").setDescription("abraham.licoln@gmail.com")
                .setOnProfileClickListener(new DrawerProfile.OnProfileClickListener() {
                    @Override
                    public void onClick(final DrawerProfile drawerProfile) {
                        // Toast.makeText(MainActivity.this, "Clicked profile", Toast.LENGTH_SHORT).show();
                         }});
        drawerLayout.setStatusBarBackgroundColor( Color.parseColor("#388E3C"));
        Toolbar toolbar = (Toolbar) findViewById(R.id.my_awesome_toolbar);
        toolbar.setNavigationIcon(R.drawable.ic_silent_hill);
        setSupportActionBar(toolbar);



        getSupportActionBar().setTitle("Silent Hill");

        drawer.addItem(
                new DrawerItem()
                        .setImage(getResources().getDrawable(R.drawable.ic_action_cache))
                        .setTextPrimary("Download Cards")
                        .setTextSecondary("Cache your cards for offline use.")
                        .setOnItemClickListener(new DrawerItem.OnItemClickListener() {
                            @Override
                            public void onClick(DrawerItem drawerItem, int id, int position) {
                                Toast.makeText(MainActivity.this, "Caching coming soon!", Toast.LENGTH_SHORT).show();
                            }
                        })
        );
     
     --- Code to add drawer items


        drawer.setProfile(  profile     );


    }


========================

**Comment by HeinrichReimer** [comment]
OK, thank you.
Is R.drawable.bamboo a bitmap?
I'll look if I can reproduce this error and than how I can fix it.

**Comment by HeinrichReimer** [comment]
BTW the demo is available now

**Comment by stripathi669** [comment]
Yes, the R.drawable.bamboo is a bitmap. I have tried several other formats too.

I remember the option worked for me initially. However after sometime, it stopped showing up. I have tried to reverse all steps. But I can't seem to locate the problem.

**Comment by HeinrichReimer** [comment]
Check `onOptionsItemSelected()` method in your activity/fragment. If you use `ActionDrawerToggle` you have to call its `onOptionsItemSelected()` method.

    
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (drawerToggle.onOptionsItemSelected(item)) {
            return true;
        }
        // Check other manu items 
    }

**Comment by stripathi669** [comment]
Okay Thanks. 
All issues resolved. Thank you so much.

**Comment by HeinrichReimer** [comment]
No problem ;)
