### ISSUE TITLE
Drawer profile without profile Information

### ISSUE THREAD

**Issue by AngelBob** [HeinrichReimer/material-drawer#26]
When setting a drawer profile with
drawer.setProfile(
        new DrawerProfile()
                .setBackground(getResources().getDrawable(R.drawable.profile_background)));

The background image is not displayed correctly, it fill's at full height.
Tested on both 4.4 & 5.0

**Comment by HeinrichReimer** [comment]
Can you post a screenshot of this error?

**Comment by HeinrichReimer** [comment]
Anyone other experienced this?

**Comment by HeinrichReimer** [comment]
Fixed in the next update
