### ISSUE TITLE
Android studio preview

### ISSUE THREAD

**Issue by yoavst** [HeinrichReimer/material-drawer#27]
```
Exception raised during rendering: com.android.layoutlib.bridge.android.BridgeContext cannot be cast to android.app.Activity java.lang.ClassCastException: com.android.
```

**Comment by HeinrichReimer** [comment]
I guess this is because in DrawerView.java in line 411 (https://github.com/HeinrichReimer/material-drawer/blob/master/library/src/main/java/com/heinrichreimersoftware/materialdrawer/DrawerView.java#L411) the `Context` gets cast to an `Activity`.
I fixed this for the next update.
