### ISSUE TITLE
Can't add item with pre rendered icon

### ISSUE THREAD

**Issue by guilhermearaujo** [HeinrichReimer/material-drawer#29]
I would like to add an item whose icon is coloured, but keep the same dimensions as a regular icon.
If I choose to draw as a `DrawerItem.AVATAR`, the image will look the way I want, but the row will be taller. If I choose `DrawerItem.ICON`, the height will be as I want, but the icon will not be rendered with colours.

Is it possible to have a third option that features what I described?

**Comment by HeinrichReimer** [comment]
I'll add a third option: DrawerItem.SMALL_AVATAR

**Comment by HeinrichReimer** [comment]
Fixed! Wait for the next update soon.
