### ISSUE TITLE
Can't change width of the drawer

### ISSUE THREAD

**Issue by Reverp** [HeinrichReimer/material-drawer#30]
Hi, I'm trying to use your library in my app since it looks great. However, the navigation drawer is completely filling the screen of my phone. Is this supposed to happen or is there any way I can set the width of the drawer myself? 

It's pretty odd though, I did the same exact thing as you did in the sample application.

Please let me know, thanks.

**Comment by guilhermearaujo** [comment]
I would like to change the width too.

**Comment by Reverp** [comment]
Have you tried it? Is it filling your whole screen too?

**Comment by guilhermearaujo** [comment]
No, I simply don't know how to change it. I'm testing on a tablet, so it doesn't fill the whole screen width. But it fills almost 3/4 of it, and that is somewhat unnecessary to me.

How did you change?

**Comment by HeinrichReimer** [comment]
I'll implement this in the next update
