### ISSUE TITLE
Support multiple profiles

### ISSUE THREAD

**Issue by maxpower47** [HeinrichReimer/material-drawer#33]
It looks like only a single profile can be specified, for apps (like most of Googles) that support multiple accounts it would be useful to have the drawer profile able to switch between them.

**Comment by HeinrichReimer** [comment]
Very nice idea!

**Comment by HeinrichReimer** [comment]
Implemented in 351996e3596bc8096e0d8b48e1f239b9289f6154

**Comment by maxpower47** [comment]
Nicely done!  I like the animations and polish.  I've found a few bugs and other enhancement opportunities related to this, I went ahead and opened new issues for each.  Thanks

**Comment by HeinrichReimer** [comment]
Thanks for the issues. They speed up bug fixing ;)
