### ISSUE TITLE
Profile don't have mDrawerView

### ISSUE THREAD

**Issue by tsuharesu** [HeinrichReimer/material-drawer#34]
When I update anything on a Profile the `notifyDataChanged` is never called because the profile isn't attached to a DrawerView. So, looking at the Items code, I would call the `mProfile.attachTo(mDrawerProfile)`, but this trigger a infinite loop between `attachTo`, `notifyDataChanged` and `setProfile`.

I don't think we need the `notifyDataChanged` on the `profile.attachTo`, so I removed it. Don't know if this is the best alternative, but it is working :+1:

**Comment by HeinrichReimer** [comment]
8cdf1b1cbabf94bae2a459af4fd69234e42a29f7 solves this.
