### ISSUE TITLE
Crash with no profile

### ISSUE THREAD

**Issue by maxpower47** [HeinrichReimer/material-drawer#39]
As of 2.0 it looks like a force close happens if a profile is not added, or not added soon enough in the activity lifecycle.

**Comment by HeinrichReimer** [comment]
I'm sorry! I didn't check that. I'll upload a fix later today

**Comment by HeinrichReimer** [comment]
Fixed this for the next update.

**Comment by timgreen** [comment]
Looking forward to see the update.

btw, I suggest to leave the bug open until the update has been pushed.

**Comment by HeinrichReimer** [comment]
Fixed in version 2.0.2
