### ISSUE TITLE
Bibliotek/Bugs/Crash

### ISSUE THREAD

**Issue by MishUshakov** [HeinrichReimer/material-drawer#42]
Guten Tag,ich benutze dieser Bibliotek in meinem App 
Das App crasht on Method onCreate ich habe das Bibliotek auf diese Gerate getestet
-Sony Xperia miro 4.0.4 Fliegt raus
-Samsung Galaxy Tab PRO 4.4.4-Funktioniert Gut
-LG G2 4.2.2 Fliegt raus...
Viele benutzer haben bei mich gemeldet
Ich erwarte von innen Unterstützung für Android 4.0+ bzw.fur Sony,LG,usw.

**Comment by HeinrichReimer** [comment]
Hi gibt es von ihren Usern auch stacktraces etc.?

**Comment by MishUshakov** [comment]
Überraschend weise crasht das App nur auf Android 4.0+ ,Aber auf 4.4 ist alles gut
Ich kann gern das Projekt auf GitHub hochladen

**Comment by HeinrichReimer** [comment]
Gerne, dann ist der Fehler schneller gefunden

**Comment by MishUshakov** [comment]
Hallo,sie können gern mein Projekt hiere herunterladen 
https://docs.google.com/file/d/0Bw5JtLywXMnjelU0MVRZdlpEQzQ/edit?usp=docslist_api

**Comment by MishUshakov** [comment]
Hallo Heinrich,das Fehler wurde gefunden das lag im App ,aber auf keinen Fall in ihre Bibliothek,danke für Unterstützung

**Comment by MishUshakov** [comment]
Hallo Heinrich,das Fehler wurde gefunden das lag im App ,aber auf keinen Fall in ihre Bibliothek,danke für Unterstützung
