### ISSUE TITLE
NPE when switch profile

### ISSUE THREAD

**Issue by timgreen** [HeinrichReimer/material-drawer#45]
version: 2.0

    E/AndroidRuntime( 2441): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
    E/AndroidRuntime( 2441):        at com.nineoldandroids.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:533)
    E/AndroidRuntime( 2441):        at com.nineoldandroids.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:410)
    E/AndroidRuntime( 2441):        at com.nineoldandroids.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:538)
    E/AndroidRuntime( 2441):        at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:928)
    E/AndroidRuntime( 2441):        at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:951)
    E/AndroidRuntime( 2441):        at com.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:385)
    E/AndroidRuntime( 2441):        at com.nineoldandroids.animation.AnimatorSet.start(AnimatorSet.java:502)
    E/AndroidRuntime( 2441):        at com.heinrichreimersoftware.materialdrawer.DrawerView.animateToProfile(DrawerView.java:687)
    E/AndroidRuntime( 2441):        at com.heinrichreimersoftware.materialdrawer.DrawerView.selectProfile(DrawerView.java:895)
    E/AndroidRuntime( 2441):        at com.heinrichreimersoftware.materialdrawer.DrawerView$3.onItemClick(DrawerView.java:172)
    E/AndroidRuntime( 2441):        at com.heinrichreimersoftware.materialdrawer.widget.LinearListView$InternalOnClickListener.onClick(LinearListView.java:283)
    E/AndroidRuntime( 2441):        at android.view.View.performClick(View.java:4756)
    E/AndroidRuntime( 2441):        at android.view.View$PerformClick.run(View.java:19749)
    E/AndroidRuntime( 2441):        at android.os.Handler.handleCallback(Handler.java:739)
    E/AndroidRuntime( 2441):        at android.os.Handler.dispatchMessage(Handler.java:95)
    E/AndroidRuntime( 2441):        at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime( 2441):        at android.app.ActivityThread.main(ActivityThread.java:5221)
    E/AndroidRuntime( 2441):        at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime( 2441):        at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime( 2441):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    E/AndroidRuntime( 2441):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by HeinrichReimer** [comment]
Fixed in Version 2.0.2
