### ISSUE TITLE
RTL support for the drawer (open drawer from right of the screen)

### ISSUE THREAD

**Issue by navidei** [HeinrichReimer/material-drawer#47]
Can you explain how can I implement this great navigation drawer to be opened from right to left of the screen. I have tried many ways like android:layout_gravity:right,         getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);, or giving LayoutParams to the drawer object but none of them worked for me.

**Comment by HeinrichReimer** [comment]
Release [**2.2.0**](/HeinrichReimer/material-drawer/releases/tag/2.2.0) includes support for RTL text and automatically aligns the drawer to the right on RTL locales.

**Comment by navidei** [comment]
Wow! That's great and thank you.

**Comment by sajadabasi** [comment]
how to have RTL support on not RTL languages?
