### ISSUE TITLE
Can't add fixed items.

### ISSUE THREAD

**Issue by EmanueleHB** [HeinrichReimer/material-drawer#48]
It's impossible to add a fixed Item from DrawerFrameLayout. There's no method for it.

I think this would do the trick
```java
    /**
     * Adds a fixed item to the drawer
     *
     * @param item Item to add
     */
    public DrawerFrameLayout addFixedItem(DrawerItem item) {
        mDrawer.addFixedItem(item);
        return this;
    }
```

**Comment by gandulf** [comment]
you can use the methods from DrawerView for now, just call 

    mDrawer = (DrawerView) findViewById(R.id.mdDrawer);

after you infalted the DrawerFrameLayout and use the methods provided by DrawerView.
To make this easier I added a getDrawer() method to the DrawerFrameLayout.

**Comment by HeinrichReimer** [comment]
Fixed that for the next update.
