### ISSUE TITLE
Method to make drawer appear?

### ISSUE THREAD

**Issue by alvinwoon** [HeinrichReimer/material-drawer#49]
Would be nice if there's a function we can call to surface the drawer other than the slide gesture. I am thinking of adding a button on the footer for users less familiar with android design guideline.

**Comment by mendhak** [comment]
Do you mean toggle the drawer's visibility?  For example I am handling the `KeyEvent.KEYCODE_MENU` in `onKeyUp` of my Activity.  In there, 

        DrawerLayout drawerLayout = (DrawerLayout) findViewById(R.id.drawer_layout);
        if(drawerLayout.isDrawerOpen(Gravity.LEFT)){
            drawerLayout.closeDrawer(Gravity.LEFT);
        }
        else {
            drawerLayout.openDrawer(Gravity.LEFT);
        }

**Comment by alvinwoon** [comment]
Thanks!
