### ISSUE TITLE
Info: I have not much time for this project

### ISSUE THREAD

**Issue by HeinrichReimer** [HeinrichReimer/material-drawer#51]
I currently have not much time for this project. I am very busy at my college.

**Comment by alexliao** [comment]
Understand. No more request, just one bug fixing, can you please fix the single profile issue #43 and update the gradle ? Really appreciate it because this small detail affect my project significantly.

**Comment by HeinrichReimer** [comment]
I'l release the next update in a day or two.

**Comment by alexliao** [comment]
Thank you very much!
2015年4月9日 下午9:38于 "Heinrich Reimer" <notifications@github.com>写道：
