### ISSUE TITLE
Project refresh failed

### ISSUE THREAD

**Issue by IgorGanapolsky** [HeinrichReimer/material-drawer#58]
Hello,
upon importing your project into Android Studio, I get the following error:
> Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

Please advise.

**Comment by HeinrichReimer** [comment]
This error occurs because gradle is missing the projects *gradle.properties*

**Comment by IgorGanapolsky** [comment]
Where is your supplied gradle.properties?  I got rid of the error by commenting out `//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'`

**Comment by HeinrichReimer** [comment]
I'll upload the `gradle.properties` file.

**Comment by HeinrichReimer** [comment]
Should be fixed now

**Comment by IgorGanapolsky** [comment]
I am still getting the error:
> Error:No such property: POM_ARTIFACT_ID for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by HeinrichReimer** [comment]
Sorry, I forgot to add the *library/gradle.properties*

**Comment by IgorGanapolsky** [comment]
Now it works!

**Comment by HeinrichReimer** [comment]
Great!
