### ISSUE TITLE
Latest library not pulled from MavenCentral

### ISSUE THREAD

**Issue by IgorGanapolsky** [HeinrichReimer/material-drawer#61]
Hello if you look at sourcecode for DrawerActivity on GitHub, you can see that it extends `AppCompatActivity`.  However, in my project, when I pull the library in gradle from MavenCentral, I see that DrawerActivity extends from `ActionBarActivity`.  Please explain.

**Comment by HeinrichReimer** [comment]
The current source code contains bugs as described in #60.
Therefore it hasn't been pushed to Maven yet.
