### ISSUE TITLE
Status bar background

### ISSUE THREAD

**Issue by superalin98** [HeinrichReimer/material-drawer#64]
Is it possible to make an option at least to set the drawer status bar fully transparent? Like the new Google apps like Docs and Slides?

**Comment by HeinrichReimer** [comment]
This is something the guidelines clearly discourage. Anyway you may add the option to set a different status bar color and send a pull request.

**Comment by HeinrichReimer** [comment]
Release [**2.2.0**](/HeinrichReimer/material-drawer/releases/tag/2.2.0) includes support for theming the translucent status bar in [`DrawerTheme`](/HeinrichReimer/material-drawer/blob/master/library/src/main/java/com/heinrichreimersoftware/materialdrawer/theme/DrawerTheme.java).
Simply use `setStatusBarBackgroundColorRes()` or `setStatusBarBackgroundColor()`.
