### ISSUE TITLE
Can't setAvater on DrawerProfile

### ISSUE THREAD

**Issue by safarious** [HeinrichReimer/material-drawer#65]
I can't set the DrawerProfile-Avatar in onActivityResult(). There is just happening nothing. It is also not possible to remove the Avatar.

onProfileClickListener:
```
            public void onClick(DrawerProfile drawerProfile, long l) {
                mDrawerProfile = drawerProfile;
                Intent pictureActionIntent = new Intent(
                        android.provider.MediaStore.ACTION_IMAGE_CAPTURE);
                startActivityForResult(pictureActionIntent,
                        CAMERA_REQUEST);
            }
```
onActivityResult:
```
if (requestCode == CAMERA_REQUEST && resultCode == RESULT_OK
                && null != data) {
            Bitmap mBitmap = (Bitmap) data.getExtras().get("data");
            mDrawerProfile.removeAvatar();
            mDrawerProfile.setRoundedAvatar(new BitmapDrawable(mBitmap));
}
```

**Comment by HeinrichReimer** [comment]
Looks like you are defininging `mDrawerProfile` in the `OnProfileClickListener`. You shouldn't copy the profile like this. Try to use `findProfileById()` and save the current profile ID instead.

**Comment by HeinrichReimer** [comment]
Are you sure that you defined `mDrawerProfile` before `onActivityResult()`?

**Comment by safarious** [comment]
Thank you for your answer. In fact I did define mDrawerProfile before. I tried your idea to use ```findProfileById()``` , but this doesn't work as well.

I think the problem is that ```onActivityResult()``` is called before ```onResume()```. As far as I saw you load many things in there and it probably gets overwritten - but I'm just speculating. Do you have any further idea's how to solve that?

**Comment by HeinrichReimer** [comment]
You're right. It seeks like the `DrawerProfile` doesn't get attached before `onResume()`.
Probably you can save the `Bitmap` that you get using `(Bitmap) data.getExtras().get("data");` and later in `onResume()` set this as profile avatar.
BTW I'm wondering how you get the `Bitmap` from the `Bundle` returned by `data.getExtras()`. Shouldn't it be `getParcelable("data")` instead of `getParcelable("data")`?
