### ISSUE TITLE
Mutiple Drawer Items

### ISSUE THREAD

**Issue by amineMpdam** [HeinrichReimer/material-drawer#66]
when adding mutiple Draweritems (seperatly or using a list of drawer items ) only the last added item is displayed!! using the addItem/addItems methods only the last DrawerItem is displayed!!

**Comment by HeinrichReimer** [comment]
Could you post your code here?

**Comment by amineMpdam** [comment]
Sure thing i've added a fixed item and 3 other items using 

 setDrawerTheme(
                new DrawerTheme(this)
                        .setBackgroundColorRes(R.color.my_primary_light_color)

        );

   setSupportActionBar((Toolbar) findViewById(R.id.toolbar_home));
        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setTitle("Dash Board");


        setDrawerTheme(
                new DrawerTheme(this)
                        .setBackgroundColorRes(R.color.my_primary_light_color)

        );



        addItems(new DrawerItem()
                        .setTextPrimary(getString(R.string.messages))
                        .setTextSecondary(getString(R.string.detail_messages))
                        .setImage(getResources().getDrawable(R.drawable.messages))
                        .setOnItemClickListener(new DrawerItem.OnItemClickListener() {
                            @Override
                            public void onClick(DrawerItem drawerItem, long l, int i) {
                                Intent toMessages = new Intent(getApplicationContext(), MessagesActivity.class);
                                startActivity(toMessages);
                            }
                        }), new DrawerItem()
                        .setTextPrimary(getString(R.string.stats))
                        .setTextSecondary(getString(R.string.detail_stats))
                        .setImage(getResources().getDrawable(R.drawable.stats))

        );

        addFixedItems(new DrawerItem()
                        .setTextPrimary(getString(R.string.emplpoi))
                        .setTextSecondary(getString(R.string.detail_emploi))
                        .setImage(getResources().getDrawable(R.drawable.scedule)),
                new DrawerItem()
                        .setTextPrimary(getString(R.string.accueil))
                        .setTextSecondary(getString(R.string.detail_acceuil))
                        .setImage(getResources().getDrawable(R.drawable.home))


        );



   


        

only the last item is displayed when (the last item & the last FixedItem)

**Comment by amineMpdam** [comment]
so ???

**Comment by HeinrichReimer** [comment]
Could you try to add a unique ID to every item with `setId(long id)`?
Each item gets its own ID when it's added to the list. I currently use `System.nanoTime()` as 'default' ID. May this be the issue?

**Comment by amineMpdam** [comment]
okay sure i'll try that and give you a feed back 
thanx bra !!

**Comment by HeinrichReimer** [comment]
I modified the random default id to `System.nanoTime() * 100 + Math.round(Math.random() * 100)` ro ensure no item gets added with the same ID
