### ISSUE TITLE
Dependency not working for my project

### ISSUE THREAD

**Issue by macaronlover** [HeinrichReimer/material-drawer#68]
For some reason I get an error after adding the dependency to my project. What's gone wrong here?

![screen shot 2015-07-20 at 12 33 09](https://cloud.githubusercontent.com/assets/12353505/8774954/8aec1b90-2edb-11e5-85f3-3ed2a3b974f7.png)

**Comment by HeinrichReimer** [comment]
There are some issues with the Maven Central link as I'm moving this repo to jCenter..
I apologize for all inconveniences...

**Comment by bogdanzurac** [comment]
Any updates on this matter?

**Comment by HeinrichReimer** [comment]
I now use the amazing tool **[jitpack.io](http://jitpack.io)** for automated builds and maven deploying. Read the specific section in the `README.md`.
