### ISSUE TITLE
Bug setOnProfileClickListener

### ISSUE THREAD

**Issue by zenderman** [HeinrichReimer/material-drawer#71]
Select any profile and clicking on the header information is always shown first profile and not the current one.

drawer.setOnProfileClickListener(new DrawerProfile.OnProfileClickListener() {
     @Override
     public void onClick(DrawerProfile profile, long id) {
             Toast.makeText(act, "* Clicked profile *" + id +" / "+ profile.getId() + " / " + profile.getName(), Toast.LENGTH_SHORT).show();
       }
});

**Comment by HeinrichReimer** [comment]
Release [**2.2.0**](/HeinrichReimer/material-drawer/releases/tag/2.2.0) fixes this bug.
