### ISSUE TITLE
Manifest Merger issues

### ISSUE THREAD

**Issue by bogdanzurac** [HeinrichReimer/material-drawer#72]
Hey. I wanted to try out the library, but ran into the manifest merger issue regarding the "allowBackup"  attr, which conflict with the ones in our app. This is mainly caused by an issue in the gradle Manifest Merger, as it doesn't accept the replace function for replacing that attr.

However, until the issue inside gradle is fixed, could you push a build with the "allowBackup" attr removed, so that we can use your library? Furthermore, that attr isn't even needed inside a library, so might as well remove it.

**Comment by HeinrichReimer** [comment]
Release [**2.2.0**](/HeinrichReimer/material-drawer/releases/tag/2.2.0) fixes manifest merging.
