### ISSUE TITLE
Marshalling Error

### ISSUE THREAD

**Issue by serayuzgur** [HeinrichReimer/material-drawer#73]
Hi,
Our application gets a random exception. We couldn't find the real reason for this error. Here is the exception. Can you please help us to correct this.
```log
java.lang.RuntimeException: Parcel: unable to marshal value com.heinrichreimersoftware.materialdrawer.structure.DrawerItem@b3187128
            at android.os.Parcel.writeValue(Parcel.java:1273)
            at android.os.Parcel.writeList(Parcel.java:660)
```
Thank you.

**Comment by HeinrichReimer** [comment]
You are trying to parcel `DrawerItem`s, right? That isn't supported right now.
Feel free to send a pull request that implements `Parcellable`

**Comment by serayuzgur** [comment]
I created the request. It is a quick fix, don't judge me :)
Thanks.
