### ISSUE TITLE
Blank Drawer after switching Context

### ISSUE THREAD

**Issue by FaizanMubasher** [HeinrichReimer/material-drawer#76]
When I came back from another activity. The Drawer's content is lost. It becomes nothing but full white Drawer.

**Comment by HeinrichReimer** [comment]
Can you record a video of your screen or post relevant parts of your code here to describe your problem more detailed? Would also be nice if you post your Android version and the library version you are using. Thanks in advance!

**Comment by FaizanMubasher** [comment]
I have solved it. It was my bad. Thanks.

**Comment by HeinrichReimer** [comment]
No problem :smiley:

**Comment by FaizanMubasher** [comment]
Thanks! But when I compile it on 22, it doesn't work on pre-lollipop devices.

**Comment by HeinrichReimer** [comment]
You should open another issue for that
