### ISSUE TITLE
No way to disable drawer in an activity if I put this code in my BaseActivity

### ISSUE THREAD

**Issue by qazimusab** [HeinrichReimer/material-drawer#77]
I put the drawer in my Base Activity and I only want to enable it in certain activities. Can we make this possible?

**Comment by HeinrichReimer** [comment]
If you use `DrawerFrameLayout` as root view you can then lock the drawer with this code:

````java
mDrawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
````

See this stackoverflow question for more information:  http://stackoverflow.com/q/17051104
