### ISSUE TITLE
Support for expandable menu items

### ISSUE THREAD

**Issue by mehrdadsafari** [heinrichreimer/material-drawer#78]
hi 
very thanks for good lib.
this lib very nice.
how use spinner for hide and show list item?

**Comment by HeinrichReimer** [comment]
You mean expandable items?

**Comment by mehrdadsafari** [comment]
Yes how use?!

**Comment by HeinrichReimer** [comment]
This library currently doesn't support expandable menu items. If you want, you fork this repository and change the code to add support for expandable items.
