### ISSUE TITLE
Support for window-flag "NO_LIMITS"?

### ISSUE THREAD

**Issue by 2SFN** [HeinrichReimer/material-drawer#80]
Is it possible to add support for this mode
(`WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS`)?
If it is activated, the last drawer item is mostly behind the navigation bar and nearly unreachable.
It would be nice to have a free space at the end of the list, so the last item would be usable, but the nice effect of the transparent navigation bar would be also there...

**Comment by HeinrichReimer** [comment]
Unfortunately it is not possible to get the window insets (status bar and navigation bar) as with transparent status bar. You could make the activity fullscreen by setting the [`SYSTEM_UI_FLAG_HIDE_NAVIGATION`](https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_HIDE_NAVIGATION) as an alternative.
