### ISSUE TITLE
setProfile not working.

### ISSUE THREAD

**Issue by Alikaraki95** [heinrichreimer/material-drawer#93]
i just found this library, addItem is working fine but when i use setProfile it doesn't work.

Cannot resolve method.
Error:(616, 9) error: cannot find symbol method setProfile(DrawerProfile)

**Comment by heinrichreimer** [comment]
`setProfile()` was removed in favor of `addProfile()`.
In your case it should be replaced with:
```java
clearProfiles();
addProfile();
```
I'll update the Readme 😉

**Comment by Alikaraki95** [comment]
@heinrichreimer Thanks alot !  Worked.
