### ISSUE TITLE
Download drawer avatar with Glide & Firebase

### ISSUE THREAD

**Issue by Vel-San** [heinrichreimer/material-drawer#95]
Hey, 

Thanks alot for this library, however I've facing an issue. i already set up the drawer and i implemented the onClickListener for the header to upload an image to Firebase, which works fine, but i want to add this image to the drawer avatar ( as a profile image ) also retrieve the image automatically on onCreate() to put in the Drawer header avatar, so i couldn't find how do i:

1. Refresh the drawer texts elements ( i change something and the title/description of the items change only after i restart the app
2. Update the avatar after i successfully get the image using this
```java
public void set_profileImg(){
    StorageReference mStorage = storageReference.child("images/" + user.getUid() + "/*");
    mStorage.getDownloadUrl().addOnSuccessListener(new OnSuccessListener<Uri>() {
        @Override
        public void onSuccess(Uri uri) {
            Glide.with(MainActivity.this).load(uri).into(AVATAR_GOES_HERE);
        }
    }).addOnFailureListener(new OnFailureListener() {
        @Override
        public void onFailure(@NonNull Exception exception) {
            // Handle any errors
        }
    });
}
```

Do you have any idea on how to fix this/workaround for this ? Thanks again.

**Comment by heinrichreimer** [comment]
I think what you're searching for is Glide's `#asBitmap()` and then `DrawerProfile#setRoundedAvatar(Drawable)`.

**Comment by Alikaraki95** [comment]
I couldn't find the proper Glide documentation or methods to use, I didn't know there was such a method. I'll try it and get back to you. Thanks for the response!

**Comment by heinrichreimer** [comment]
There it is: https://bumptech.github.io/glide/

**Comment by Alikaraki95** [comment]
Couldn't make it work, Glide always giving error the .into() as a drawable and not a view, also, even if it works, i couldn't find a way to refresh the drawer layout to get new values ( new secondaryText for an item, new profile picture ) unless i restart the app

**Comment by heinrichreimer** [comment]
You should use Glide's `#into(Int, Int)`.
You can replace the drawer profile by removing the old one first and then adding the new one.

**Comment by Alikaraki95** [comment]
Oh okay, i'll try that. Thanks for the response.
