### ISSUE TITLE
OnBackPress from fragment how to set default item checked 

### ISSUE THREAD

**Issue by vikas05** [heinrichreimer/material-drawer#96]
when switch from fragment and then back pressed the navigation item selection not removing

**Comment by heinrichreimer** [comment]
I would assume the `Fragment`'s or `Activity`'s `onSaveInstanceState()` method as described in the [Android guidelines](https://developer.android.com/guide/components/activities/activity-lifecycle.html#saras) would be the appropriate place to save the selected item.
